### ISSUE TITLE
In benchmarking_server.py line 279 return None modelB

### ISSUE THREAD

**Issue by cucrui** [qub-blesson/AdaptiveDNN#1]
I try to run this  code with `sudo python benchmarking_server.py lenet` and rise an exception in "benchmarking_server.py" line 93. The error report is "'Dense' object is not iterable".
When I change line 93 to `prev_layers.extend([node.inbound_layers])`, the code run correct.
Pls check whether this line has a bug. Thanks a lot.

**Comment by FrancisMcN** [comment]
Hi,

I think that issue is caused by having incompatible versions of Tensorflow/Keras. I've updated the readme file with instructions to create a virtual environment first and I've included a `requirements.txt` file with all the necessary dependencies.

I tested locally and the code runs for me after running in a virtual environment. 

Thanks for pointing out this issue because the readme should've had this information already.
